name: "Check"
on:
  pull_request:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
    - name: Building Nixpkgs manual
      run: |
        nix-shell update.nix --pure
        nix-build release.nix -A gecko.x86_64-linux.clang -o firefox-x64
